# -*- coding: utf-8 -*-
"""Tugas Pengenalan Pola.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xR2TSUdAvutihTBo-9sNc-xWr242zMcu

F55119001_F55119012_F55119013
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

dataset = pd.read_csv('DataTinggiBadan1.csv')
x = dataset.iloc[:, [0, 1]].values
y = dataset.iloc[:, -1].values

dataset.head()

#Mencetak data x
print(x)

#Mencetak data y
print(y)

from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, random_state=0)

#Mencetak dataset training
print(x_train)

#Mencetak dataset testing
print(x_test)

sns.pairplot(dataset,vars=['Tinggi badan','Usia'], hue='Tinggi badan')
plt.ioff

sns.countplot(dataset['Tinggi badan'])
plt.ioff()